name: Deploy Migrations to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to staging project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: See diff
        run: supabase db diff --linked

      - name: Run lint
        run: supabase db lint --fail-on error

      - name: Run tests
        run: supabase test db

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Generate backup
        run: bun db:dump-remote

      - name: Archive backup
        uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: supabase/dump/
          retention-days: 5

      - name: Push migrations to staging
        run: supabase db push
